[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "relocation-model=static",
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-static"
]

[target.aarch64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "relocation-model=static",
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-static"
]